### ISSUE TITLE
Multiple Select & Disable Backdrop

### ISSUE THREAD

**Issue by tragicmj** [TheWidlarzGroup/rn-emoji-keyboard#58]
**Is your feature request related to a problem? Please describe.**
My application has a chat screen, so every time I want to select multiple emojis, I cannot as the picker closes as soon as I select one emoji. In addition to that, I am unable to scroll my chat when it is open.

**Describe the solution you'd like**
Ability to select multiple emojis and disable the backdrop to scroll chat.

**Additional context**
![simulator_screenshot_A8EEB404-05F4-442C-9286-EDCD026F45A6](https://user-images.githubusercontent.com/44090234/164419676-192d6264-a782-44fa-a8b7-4addfede9ac5.png)

**Comment by jakex7** [comment]
Hi, thank you for choosing our library. An ideal solution to your problem would be to use static `EmojiKeyboard` (which is already done) instead of `EmojiPicker`.
You can import that from library and use it in similar way like EmojiPicker
Here is a short example of usage
```js
import { EmojiKeyboard } from 'rn-emoji-keyboard'
const StaticKeyboard = () => {
      // rest of code
      return (
         <View>
            <EmojiKeyboard onEmojiSelected={handlePick} containerStyles={styles.keyboardContainer} />
         </View>
      )
}
```
And here is a full example
https://github.com/TheWidlarzGroup/rn-emoji-keyboard/blob/master/example/src/Static/Static.tsx

![Static EmojiKeyboard preview](https://raw.githubusercontent.com/TheWidlarzGroup/rn-emoji-keyboard/master/example/assets/static-preview.jpg)

If you have any additional questions, feel free to ping me here 😄

**Comment by jakex7** [comment]
I'm closing this issue due to providing a solution and no additional questions from the author.
If you have any questions, please feel free to reopen the issue.
