### ISSUE TITLE
can support list of emoji ?

### ISSUE THREAD

**Issue by iim-norse** [TheWidlarzGroup/rn-emoji-keyboard#62]
To possible validation on backend we need have same emojis list on backend and frontend like: https://cdn.jsdelivr.net/npm/@emoji-mart/data

**Comment by jakex7** [comment]
Hi, there is a full list of available emojis in assets folder named [emojis.json](https://github.com/TheWidlarzGroup/rn-emoji-keyboard/blob/master/src/assets/emojis.json) (or you can access it via cdn like in your example https://cdn.jsdelivr.net/npm/rn-emoji-keyboard/src/assets/emojis.json) 
I hope that's what you meant 🙈
If you have any additional questions, I will be happy to answer 😃

**Comment by iim-norse** [comment]
ok so have same names, would be good to have ids, but that's ok

**Comment by jakex7** [comment]
Actually name should be unique for each emoji

**Comment by grantmagdanz** [comment]
Running into a similar issue.

We are implementing chat reactions across web and mobile. We need to use the same ID across both in order to render the reaction properly. There isn't a standard here it doesn't seem. We're currently using emoji-mart on web and were hoping to be able to supply rn-emoji-keyboard with a set of data (instead of the one in `assets/emojis.json`) in order to ensure the same set.

Is there any way to do this or any work around?
